#!/bin/bash
set -eux
ninja -C build
exec env -i "HOME=/host/home/roman" "QNX_ROOT=$QNX_ROOT" "PATH=/bin:/usr/bin" "TERM=$TERM" \
    build/qine -m /,$QNX_ROOT -m /host,/,exec=qnx \
    $QNX_SLIB \
    "$@"

